# Generated by Django 5.2.16 on 2026-07-20 01:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def create_default_wallets(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Wallet = apps.get_model("expenses", "Wallet")
    Expense = apps.get_model("expenses", "Expense")

    for user in User.objects.all():
        wallet, _ = Wallet.objects.get_or_create(
            user=user,
            name="Default Wallet",
            defaults={
                "account_type": "cash",
                "opening_balance": Decimal("0.00"),
                "current_balance": Decimal("0.00"),
                "currency": getattr(user, "currency", "USD"),
                "description": "Default wallet created automatically for existing records.",
                "is_active": True,
            },
        )
        Expense.objects.filter(
            user=user, wallet__isnull=True).update(wallet=wallet)

    for wallet in Wallet.objects.all():
        total_income = wallet.expenses.filter(transaction_type="income").aggregate(
            total=models.Sum("amount"))['total'] or Decimal("0.00")
        total_expense = wallet.expenses.filter(transaction_type="expense").aggregate(
            total=models.Sum("amount"))['total'] or Decimal("0.00")
        wallet.current_balance = wallet.opening_balance + total_income - total_expense
        wallet.save(update_fields=["current_balance"])


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('mobile', 'Mobile Money'), (
                    'card', 'Credit Card'), ('savings', 'Savings'), ('other', 'Other')], default='cash', max_length=12)),
                ('opening_balance', models.DecimalField(
                    decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(
                    decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='expenses', to='expenses.wallet'),
        ),
        migrations.RunPython(create_default_wallets,
                             reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='expense',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='expenses', to='expenses.wallet'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(
                fields=('user', 'name'), name='unique_wallet_name_per_user'),
        ),
    ]
