# Generated by Django 6.0.7 on 2026-07-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='imports/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], max_length=5)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('transaction_type', models.CharField(default='expense', max_length=10)),
                ('confidence_score', models.FloatField(default=0.0)),
            ],
        ),
    ]
