# Generated by Django 5.2.16 on 2026-07-21 19:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_initial'),
        ('expenses', '0003_wallet_expense_wallet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at'], 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'start_date')},
        ),
    ]
